/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_mylexz_utils_NodeData */

#ifndef _Included_com_mylexz_utils_NodeData
#define _Included_com_mylexz_utils_NodeData
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mylexz_utils_NodeData_TYPE_INT
#define com_mylexz_utils_NodeData_TYPE_INT 105L
#undef com_mylexz_utils_NodeData_TYPE_LONG
#define com_mylexz_utils_NodeData_TYPE_LONG 76L
#undef com_mylexz_utils_NodeData_TYPE_DOUBLE
#define com_mylexz_utils_NodeData_TYPE_DOUBLE 70L
#undef com_mylexz_utils_NodeData_TYPE_CHAR
#define com_mylexz_utils_NodeData_TYPE_CHAR 99L
#undef com_mylexz_utils_NodeData_TYPE_STRING
#define com_mylexz_utils_NodeData_TYPE_STRING 115L
#undef com_mylexz_utils_NodeData_TYPE_BOOLEAN
#define com_mylexz_utils_NodeData_TYPE_BOOLEAN 98L
#undef com_mylexz_utils_NodeData_ID_NODE
#define com_mylexz_utils_NodeData_ID_NODE 40L
#undef com_mylexz_utils_NodeData_ID_ARRAY
#define com_mylexz_utils_NodeData_ID_ARRAY 62L
#undef com_mylexz_utils_NodeData_ID_DATA
#define com_mylexz_utils_NodeData_ID_DATA 60L
#undef com_mylexz_utils_NodeData_MODE_PRIVATE
#define com_mylexz_utils_NodeData_MODE_PRIVATE 1L
#undef com_mylexz_utils_NodeData_MODE_PUBLIC
#define com_mylexz_utils_NodeData_MODE_PUBLIC 16L
/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_open
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_close
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addNode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addNode
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    delNode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_delNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    clearContents
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_clearContents
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    listContents
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mylexz_utils_NodeData_listContents
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addIntData
 * Signature: (Ljava/lang/String;Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addIntData
  (JNIEnv *, jobject, jstring, jstring, jint, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addLongData
 * Signature: (Ljava/lang/String;Ljava/lang/String;JZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addLongData
  (JNIEnv *, jobject, jstring, jstring, jlong, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addCharData
 * Signature: (Ljava/lang/String;Ljava/lang/String;CZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addCharData
  (JNIEnv *, jobject, jstring, jstring, jchar, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addBoolData
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addBoolData
  (JNIEnv *, jobject, jstring, jstring, jboolean, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addStrData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addStrData
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addDoubleData
 * Signature: (Ljava/lang/String;Ljava/lang/String;DZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addDoubleData
  (JNIEnv *, jobject, jstring, jstring, jdouble, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getIntData
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getIntData
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getBooleanData
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_NodeData_getBooleanData
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getLongData
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_mylexz_utils_NodeData_getLongData
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getDoubleData
 * Signature: (Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_com_mylexz_utils_NodeData_getDoubleData
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getCharData
 * Signature: (Ljava/lang/String;C)C
 */
JNIEXPORT jchar JNICALL Java_com_mylexz_utils_NodeData_getCharData
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getStringData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylexz_utils_NodeData_getStringData
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2C
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    isAnyErrors
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_NodeData_isAnyErrors
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    deleteData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_deleteData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    clearDataValue
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_clearDataValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    isEmptyData
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_NodeData_isEmptyData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addIntArray
 * Signature: (Ljava/lang/String;Ljava/lang/String;[IZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addIntArray
  (JNIEnv *, jobject, jstring, jstring, jintArray, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addStringArray
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addStringArray
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addCharArray
 * Signature: (Ljava/lang/String;Ljava/lang/String;[CZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addCharArray
  (JNIEnv *, jobject, jstring, jstring, jcharArray, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addDoubleArray
 * Signature: (Ljava/lang/String;Ljava/lang/String;[DZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addDoubleArray
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addLongArray
 * Signature: (Ljava/lang/String;Ljava/lang/String;[JZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addLongArray
  (JNIEnv *, jobject, jstring, jstring, jlongArray, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addBooleanArray
 * Signature: (Ljava/lang/String;Ljava/lang/String;[ZZ)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addBooleanArray
  (JNIEnv *, jobject, jstring, jstring, jbooleanArray, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getOccurences
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getOccurences__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getOccurences
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getOccurences__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getOccurences
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getOccurences__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getOccurences
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getOccurences__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getOccurences
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getOccurences__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getOccurences
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getOccurences__Ljava_lang_String_2C
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    isLocked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_NodeData_isLocked
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getErrorDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylexz_utils_NodeData_getErrorDesc
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getArrayLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getArrayLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getDataType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getDataType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getIntArray
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mylexz_utils_NodeData_getIntArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getDoubleArray
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_mylexz_utils_NodeData_getDoubleArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getLongArray
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_mylexz_utils_NodeData_getLongArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getBooleanArray
 * Signature: (Ljava/lang/String;)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_mylexz_utils_NodeData_getBooleanArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setReadArrayIteration
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setReadArrayIteration
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    readNext
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_mylexz_utils_NodeData_readNext
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    resetArrayIteration
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_resetArrayIteration
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addNodeIter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addNodeIter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    nextaddNode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_nextaddNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    saveIteration
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_saveIteration
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArray__Ljava_lang_String_2_3I
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArray__Ljava_lang_String_2_3J
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArray__Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArray__Ljava_lang_String_2_3C
  (JNIEnv *, jobject, jstring, jcharArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArray__Ljava_lang_String_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArray__Ljava_lang_String_2_3Z
  (JNIEnv *, jobject, jstring, jbooleanArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArrayAtPos
 * Signature: (Ljava/lang/String;[III)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArrayAtPos__Ljava_lang_String_2_3III
  (JNIEnv *, jobject, jstring, jintArray, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArrayAtPos
 * Signature: (Ljava/lang/String;[JII)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArrayAtPos__Ljava_lang_String_2_3JII
  (JNIEnv *, jobject, jstring, jlongArray, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArrayAtPos
 * Signature: (Ljava/lang/String;[DII)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArrayAtPos__Ljava_lang_String_2_3DII
  (JNIEnv *, jobject, jstring, jdoubleArray, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArrayAtPos
 * Signature: (Ljava/lang/String;[Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArrayAtPos__Ljava_lang_String_2_3Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jobjectArray, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArrayAtPos
 * Signature: (Ljava/lang/String;[ZII)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArrayAtPos__Ljava_lang_String_2_3ZII
  (JNIEnv *, jobject, jstring, jbooleanArray, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setArrayAtPos
 * Signature: (Ljava/lang/String;[CII)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setArrayAtPos__Ljava_lang_String_2_3CII
  (JNIEnv *, jobject, jstring, jcharArray, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_appendArray__Ljava_lang_String_2_3I
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_appendArray__Ljava_lang_String_2_3J
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_appendArray__Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_appendArray__Ljava_lang_String_2_3C
  (JNIEnv *, jobject, jstring, jcharArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_appendArray__Ljava_lang_String_2_3Z
  (JNIEnv *, jobject, jstring, jbooleanArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_appendArray__Ljava_lang_String_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getIntArrayAtPos
 * Signature: (Ljava/lang/String;II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mylexz_utils_NodeData_getIntArrayAtPos
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getCharArrayAtPos
 * Signature: (Ljava/lang/String;II)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_mylexz_utils_NodeData_getCharArrayAtPos
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getDoubleArrayAtPos
 * Signature: (Ljava/lang/String;II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_mylexz_utils_NodeData_getDoubleArrayAtPos
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getLongArrayAtPos
 * Signature: (Ljava/lang/String;II)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_mylexz_utils_NodeData_getLongArrayAtPos
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getBooleanArrayAtPos
 * Signature: (Ljava/lang/String;II)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_mylexz_utils_NodeData_getBooleanArrayAtPos
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    strCatIter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_strCatIter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    isElementExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_NodeData_isElementExists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    clearArrayValue
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_clearArrayValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    deleteArrAtPos
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_deleteArrAtPos
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
