/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mylexz_utils_PrimitiveData */

#ifndef _Included_com_mylexz_utils_PrimitiveData
#define _Included_com_mylexz_utils_PrimitiveData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_open
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_close
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getErrors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getErrors
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getContentPosition
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getContentPosition__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getContentPosition
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getContentPosition__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getContentPosition
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getContentPosition__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getContentPosition
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getContentPosition__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getContentPosition
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getContentPosition__Ljava_lang_String_2C
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getArrLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getArrLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addElement
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addElement__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addElement
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addElement__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addElement
 * Signature: (Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addElement__Ljava_lang_String_2C
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addElement
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addElement__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addElement
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addElement__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    deleteElement
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_deleteElement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getStrElement
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylexz_utils_PrimitiveData_getStrElement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getIntElement
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getIntElement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getLongElement
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_mylexz_utils_PrimitiveData_getLongElement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getDoubleElement
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_mylexz_utils_PrimitiveData_getDoubleElement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getCharElement
 * Signature: (Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_com_mylexz_utils_PrimitiveData_getCharElement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setElement
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setElement__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setElement
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setElement__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setElement
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setElement__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setElement
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setElement__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setElement
 * Signature: (Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setElement__Ljava_lang_String_2C
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addArray
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addArray__Ljava_lang_String_2_3I
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addArray
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addArray__Ljava_lang_String_2_3J
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addArray
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addArray__Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addArray
 * Signature: (Ljava/lang/String;[C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addArray__Ljava_lang_String_2_3C
  (JNIEnv *, jobject, jstring, jcharArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getAllIntContentInArr
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mylexz_utils_PrimitiveData_getAllIntContentInArr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getAllLongContentInArr
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_mylexz_utils_PrimitiveData_getAllLongContentInArr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getAllDoubleContentInArr
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_mylexz_utils_PrimitiveData_getAllDoubleContentInArr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getAllCharContentInArr
 * Signature: (Ljava/lang/String;)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_mylexz_utils_PrimitiveData_getAllCharContentInArr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getIntContentArrAtPos
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getIntContentArrAtPos
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getLongContentArrAtPos
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_mylexz_utils_PrimitiveData_getLongContentArrAtPos
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getDoubleContentArrAtPos
 * Signature: (Ljava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_mylexz_utils_PrimitiveData_getDoubleContentArrAtPos
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getCharContentArrAtPos
 * Signature: (Ljava/lang/String;I)C
 */
JNIEXPORT jchar JNICALL Java_com_mylexz_utils_PrimitiveData_getCharContentArrAtPos
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_appendArray__Ljava_lang_String_2_3I
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_appendArray__Ljava_lang_String_2_3J
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_appendArray__Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    appendArray
 * Signature: (Ljava/lang/String;[C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_appendArray__Ljava_lang_String_2_3C
  (JNIEnv *, jobject, jstring, jcharArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setArray__Ljava_lang_String_2_3I
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setArray__Ljava_lang_String_2_3J
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setArray__Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setArray
 * Signature: (Ljava/lang/String;[C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setArray__Ljava_lang_String_2_3C
  (JNIEnv *, jobject, jstring, jcharArray);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setDataAtArrPos
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setDataAtArrPos__Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setDataAtArrPos
 * Signature: (Ljava/lang/String;JI)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setDataAtArrPos__Ljava_lang_String_2JI
  (JNIEnv *, jobject, jstring, jlong, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setDataAtArrPos
 * Signature: (Ljava/lang/String;DI)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setDataAtArrPos__Ljava_lang_String_2DI
  (JNIEnv *, jobject, jstring, jdouble, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setDataAtArrPos
 * Signature: (Ljava/lang/String;CI)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setDataAtArrPos__Ljava_lang_String_2CI
  (JNIEnv *, jobject, jstring, jchar, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    isArrayType
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_PrimitiveData_isArrayType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getElementDataType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_PrimitiveData_getElementDataType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    addStrArray
 * Signature: (Ljava/lang/String;[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_addStrArray
  (JNIEnv *, jobject, jstring, jobjectArray, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getStrAtPos
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylexz_utils_PrimitiveData_getStrAtPos
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    getStrArray
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mylexz_utils_PrimitiveData_getStrArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    appendStrArray
 * Signature: (Ljava/lang/String;[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_appendStrArray
  (JNIEnv *, jobject, jstring, jobjectArray, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setStrArray
 * Signature: (Ljava/lang/String;[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setStrArray
  (JNIEnv *, jobject, jstring, jobjectArray, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    setStrArrAtPosition
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_setStrArrAtPosition
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    readString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylexz_utils_PrimitiveData_readString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_PrimitiveData_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_PrimitiveData
 * Method:    isElementExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_PrimitiveData_isElementExists
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
