/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mylexz_utils_NodeData */

#ifndef _Included_com_mylexz_utils_NodeData
#define _Included_com_mylexz_utils_NodeData
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mylexz_utils_NodeData_TYPE_INT
#define com_mylexz_utils_NodeData_TYPE_INT 105L
#undef com_mylexz_utils_NodeData_TYPE_LONG
#define com_mylexz_utils_NodeData_TYPE_LONG 76L
#undef com_mylexz_utils_NodeData_TYPE_DOUBLE
#define com_mylexz_utils_NodeData_TYPE_DOUBLE 70L
#undef com_mylexz_utils_NodeData_TYPE_CHAR
#define com_mylexz_utils_NodeData_TYPE_CHAR 99L
#undef com_mylexz_utils_NodeData_TYPE_STRING
#define com_mylexz_utils_NodeData_TYPE_STRING 115L
#undef com_mylexz_utils_NodeData_TYPE_BOOLEAN
#define com_mylexz_utils_NodeData_TYPE_BOOLEAN 98L
#undef com_mylexz_utils_NodeData_ID_NODE
#define com_mylexz_utils_NodeData_ID_NODE 40L
#undef com_mylexz_utils_NodeData_ID_ARRAY
#define com_mylexz_utils_NodeData_ID_ARRAY 62L
#undef com_mylexz_utils_NodeData_ID_DATA
#define com_mylexz_utils_NodeData_ID_DATA 60L
#undef com_mylexz_utils_NodeData_MODE_PRIVATE
#define com_mylexz_utils_NodeData_MODE_PRIVATE 1L
#undef com_mylexz_utils_NodeData_MODE_PUBLIC
#define com_mylexz_utils_NodeData_MODE_PUBLIC 16L
/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_open
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_close
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addNode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addNode
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    delNode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_delNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    clearContents
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_clearContents
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    listContents
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mylexz_utils_NodeData_listContents
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addIntData
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addIntData
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addLongData
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addLongData
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addCharData
 * Signature: (Ljava/lang/String;Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addCharData
  (JNIEnv *, jobject, jstring, jstring, jchar);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addBoolData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addBoolData
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addStrData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addStrData
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    addDoubleData
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_addDoubleData
  (JNIEnv *, jobject, jstring, jstring, jdouble);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getIntData
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mylexz_utils_NodeData_getIntData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getBooleanData
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_NodeData_getBooleanData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getLongData
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_mylexz_utils_NodeData_getLongData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getDoubleData
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_mylexz_utils_NodeData_getDoubleData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getCharData
 * Signature: (Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_com_mylexz_utils_NodeData_getCharData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    getStringData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylexz_utils_NodeData_getStringData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    setContentData
 * Signature: (Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_setContentData__Ljava_lang_String_2C
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    isAnyErrors
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_NodeData_isAnyErrors
  (JNIEnv *, jobject);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    deleteData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_deleteData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    clearDataValue
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mylexz_utils_NodeData_clearDataValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mylexz_utils_NodeData
 * Method:    isEmptyData
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mylexz_utils_NodeData_isEmptyData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
