/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mylexz_utils_NodeData_Filter */

#ifndef _Included_com_mylexz_utils_NodeData_Filter
#define _Included_com_mylexz_utils_NodeData_Filter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
